// <auto-generated />
namespace RIA.Train.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kkk201706042100pp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kkk201706042100pp));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041405598_kkk201706042100pp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
