// <auto-generated />
namespace RIA.Train.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201706032230 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201706032230));
        
        string IMigrationMetadata.Id
        {
            get { return "201706031433058_201706032230"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
